import Head from "next/head";
import { HomePage } from "@kenk2/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kenny Kim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
      </main>
    </>
  );
}
